### ISSUE TITLE
I need help urgently. Can you give me your contact information?

### ISSUE THREAD

**Issue by Kusto-M** [NinaM31/EasyOCR-Trainer#1]
I'm a recent college graduate from China. Now I am doing an OCR project for graduation project. But my coding level is really bad.
I have seen your project in website, and I run your code in my laptop, the result is as good as expected.
But I have many question about your code. I have to write a paper, while the topic is OCR.
From my perspective，you are an expert in this area to me.
So I want to get your Internet contact information that I can contact you anytime if I need ask question.
This is really important to me, you are good at OCR area, while I am very new and innocent.
Sorry for this issue unrelated to the project, but I hope I can talk to you soon.
If you use Twitter, Line，Whatsapp etc. Just tell me your number.
Thanks

**Comment by NinaM31** [comment]
Hello @cherrise28, you can contact me through my [linkedin](https://sa.linkedin.com/in/nina-almaamary-1a1149211). Good luck in your graduation project.
