### ISSUE TITLE
value error during custom training   "Usecols do not match columns, columns expected but not found: ['filename']"

### ISSUE THREAD

**Issue by anidiatm41** [NinaM31/EasyOCR-Trainer#2]
ValueError: Usecols do not match columns, columns expected but not found: ['filename']

I have labels.csv which has two columns "filename" and "words" . not sure why I am getting this error.

Even I have used below suggestion 
df = pd.read_csv(os.path.join(csv_path,'labels.csv'), sep='^([^,]+),', engine='python', usecols=['filename', 'words'],  index_col=False, keep_default_na=False)

no luck so far, pls help

**Comment by NinaM31** [comment]
Hello @anidiatm41 can you tell me in which file or function do you get this error?

**Comment by anidiatm41** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\conda\conda\envs\torch\lib\site-packages\pandas\io\parsers\python_parser.py in _handle_usecols(self, columns, usecols_key, num_original_columns)
    563                         try:
--> 564                             col_indices.append(usecols_key.index(col))
    565                         except ValueError:

ValueError: 'filename' is not in list

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18968/2139894117.py in <module>
      2 
      3 
----> 4 opt = get_config("config_files/base_config.yaml")
      5 
      6 train(opt, amp=False)

~\AppData\Local\Temp/ipykernel_18968/703623007.py in get_config(file_path)
      7         for data in opt['select_data'].split('-'):
      8             csv_path = os.path.join(opt['train_data'], data, 'labels.csv')
----> 9             df = pd.read_csv(csv_path, sep='^([^,]+),', engine='python', usecols=['filename', 'words'], keep_default_na=False)
     10             print(df.head())
     11             all_char = ''.join(df['words'])

~\AppData\Local\conda\conda\envs\torch\lib\site-packages\pandas\util\_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312 
    313         return wrapper

~\AppData\Local\conda\conda\envs\torch\lib\site-packages\pandas\io\parsers\readers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    678     kwds.update(kwds_defaults)
    679 
--> 680     return _read(filepath_or_buffer, kwds)
    681 
    682 

~\AppData\Local\conda\conda\envs\torch\lib\site-packages\pandas\io\parsers\readers.py in _read(filepath_or_buffer, kwds)
    573 
    574     # Create the parser.
--> 575     parser = TextFileReader(filepath_or_buffer, **kwds)
    576 
    577     if chunksize or iterator:

~\AppData\Local\conda\conda\envs\torch\lib\site-packages\pandas\io\parsers\readers.py in __init__(self, f, engine, **kwds)
    931 
    932         self.handles: IOHandles | None = None
--> 933         self._engine = self._make_engine(f, self.engine)
    934 
    935     def close(self):

~\AppData\Local\conda\conda\envs\torch\lib\site-packages\pandas\io\parsers\readers.py in _make_engine(self, f, engine)
   1229 
   1230         try:
-> 1231             return mapping[engine](f, **self.options)
   1232         except Exception:
   1233             if self.handles is not None:

~\AppData\Local\conda\conda\envs\torch\lib\site-packages\pandas\io\parsers\python_parser.py in __init__(self, f, **kwds)
    113             self.num_original_columns,
    114             self.unnamed_cols,
--> 115         ) = self._infer_columns()
    116 
    117         # Now self.columns has the set of columns that we will process.

~\AppData\Local\conda\conda\envs\torch\lib\site-packages\pandas\io\parsers\python_parser.py in _infer_columns(self)
    494                     columns = [names]
    495             else:
--> 496                 columns = self._handle_usecols(
    497                     columns, columns[0], num_original_columns
    498                 )

~\AppData\Local\conda\conda\envs\torch\lib\site-packages\pandas\io\parsers\python_parser.py in _handle_usecols(self, columns, usecols_key, num_original_columns)
    564                             col_indices.append(usecols_key.index(col))
    565                         except ValueError:
--> 566                             self._validate_usecols_names(self.usecols, usecols_key)
    567                     else:
    568                         col_indices.append(col)

~\AppData\Local\conda\conda\envs\torch\lib\site-packages\pandas\io\parsers\base_parser.py in _validate_usecols_names(self, usecols, names)
    911         missing = [c for c in usecols if c not in names]
    912         if len(missing) > 0:
--> 913             raise ValueError(
    914                 f"Usecols do not match columns, columns expected but not found: "
    915                 f"{missing}"

ValueError: Usecols do not match columns, columns expected but not found: ['filename']

**Comment by NinaM31** [comment]
Can you show me a snippet of the top of your csv file? or try using the sample dataset I attached, if It worked then there is an issue with your csv file. 

[en_sample.zip](https://github.com/NinaM31/EasyOCR-Trainer/files/8639089/en_sample.zip)
